# Some parts are based off https://github.com/parkervcp/yolks/blob/master/.github/workflows/java.yml

name: Build and publish Docker image

on: [push]

jobs:
  docker:
    name: "prime_${{ matrix.tag }}"
    runs-on: ubuntu-latest # guess I'll need to cope with it being Ubuntu
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 17
          - 17-libargon
          - 15
          - 15-libargon
          - 13
          - 13-libargon
          - 11
          - 11-libargon
          - 8
          - 8-libargon
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./${{ matrix.tag }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/eugeniodevv/azul-prime-pterodactyl:azul-prime_${{ matrix.tag }}
